### ISSUE TITLE
Fractured Hannya incorrect stats

### ISSUE THREAD

**Issue by jones-josh** [jy1263/rotmg-dps-calculator#2]
The fractured hannya is listed on the site as having a flat -25atk and +15dex. In game the actual stats are +25%atk and -15%dex.

This is a new type of stat change (first I'm aware that isn't a flat increase) so may not be correctly interpreted from the data files.

**Comment by amydevs** [comment]
alr, i'll check it out

**Comment by amydevs** [comment]
unfortunately i'm quite busy from studying so this might take a while :/

**Comment by amydevs** [comment]
issue continued at https://github.com/rotmg-mirror/rotmg-dps-calculator/issues/3#issue-1357839289
